version: '3.8'

services:
  web:
    build: .
    ports:
      - "${ENV_APP_PORT}:80"
    volumes:
      - uploads:/var/www/html/pages/instrucoesAdequacoes/uploads
      - petsImg:/var/www/html/pages/petControle/PETS_IMG 
      - vagasVisitante:/var/www/html/pages/ctrlVagasVisitante/vagas  
      - publicidade:/var/www/html/publicidade  
