version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - uploads:/var/www/html/pages/instrucoesAdequacoes/uploads
      - petsImg:/var/www/html/pages/petControle/PETS_IMG  
