SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `CFG_CONFIGURACAO` (
  `CFG_DCPARAMETRO` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CFG_DCVALOR` varchar(100) DEFAULT NULL,
  `CGF_DCDESC` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `COC_COTACONDOMINIO` (
  `COC_DCMES` varchar(100) DEFAULT NULL,
  `COC_NRANO` int DEFAULT NULL,
  `COC_NRVALOR` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CON_CONCILIACAO` (
  `CON_IDCONCILIACAO` int NOT NULL,
  `CON_DCTIPO` varchar(100) DEFAULT NULL COMMENT 'RECEITA OU DESPESA',
  `CON_DCMES_COMPETENCIA` varchar(100) DEFAULT NULL,
  `CON_DCDESC` varchar(200) DEFAULT NULL COMMENT 'DESCRICAO (CONDOMINIO, AGUA, ENERGIA, ETC...)',
  `CON_NMVALOR` float DEFAULT NULL,
  `CON_DTINSERT` datetime DEFAULT NULL,
  `CON_DCMES_COMPETENCIA_USUARIO` varchar(100) DEFAULT NULL,
  `CON_DCANO_COMPETENCIA_USUARIO` int DEFAULT NULL,
  `CON_DCANO_COMPETENCIA` int DEFAULT NULL,
  `CON_NMTITULO` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `eventos` (
  `id` int NOT NULL,
  `titulo` varchar(255) NOT NULL,
  `inicio` datetime NOT NULL,
  `fim` datetime NOT NULL,
  `descricao` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `FUR_FUNDO_RESERVA` (
  `FUR_IDFUNDO_RESERVA` int NOT NULL,
  `FUR_DCANO` int DEFAULT NULL,
  `FUR_DCMES` varchar(100) DEFAULT NULL,
  `FUR_DCVALUE` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `LIS_LISTACONVIDADOS` (
  `LIS_IDLISTACONVIDADOS` int NOT NULL,
  `USU_IDUSUARIO` int DEFAULT NULL,
  `LIS_DCNOME` varchar(100) DEFAULT NULL,
  `LIS_DCDOCUMENTO` varchar(100) DEFAULT NULL,
  `LIS_DTCADASTRO` datetime DEFAULT NULL,
  `LIS_STSTATUS` varchar(100) DEFAULT NULL,
  `LIS_DTULTIMA_ENTRADA` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `LOG_LOGSISTEMA` (
  `LOG_IDLOG` int NOT NULL,
  `LOG_DCTIPO` varchar(100) DEFAULT NULL,
  `LOG_DCMSG` varchar(200) DEFAULT NULL,
  `LOG_DCUSUARIO` varchar(200) DEFAULT NULL,
  `LOG_DCAPARTAMENTO` varchar(200) DEFAULT NULL,
  `LOG_DTLOG` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PUB_PUBLICIDADE` (
  `PUB_IDPUBLICIDADE` int NOT NULL,
  `PUB_DTINI` datetime DEFAULT NULL,
  `PUB_DTFIM` datetime DEFAULT NULL,
  `PUB_DCIMG` varchar(250) DEFAULT NULL,
  `PUB_DCCLIENTEORIG` varchar(100) DEFAULT NULL,
  `PUB_STSTATUS` varchar(100) DEFAULT NULL,
  `PUB_DCDESC` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MKT_IDMKTPUBLICIDADE` int DEFAULT NULL,
  `PUB_DCTIPO` varchar(100) DEFAULT NULL,
  `PUB_DCLINK` varchar(500) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `REP_REPORT` (
  `REP_IDREPORT` int NOT NULL,
  `REP_DCTIPO` varchar(100) DEFAULT NULL,
  `REP_DCDESC` varchar(100) DEFAULT NULL,
  `REP_DTDATE` date DEFAULT NULL,
  `REP_NMPRECO` float DEFAULT NULL,
  `REP_NMTITLE` varchar(100) DEFAULT NULL,
  `REP_NMVALOR` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USU_USUARIO` (
  `USU_IDUSUARIO` int NOT NULL,
  `USU_DCNOME` varchar(200) DEFAULT NULL,
  `USU_DCAPARTAMENTO` int DEFAULT NULL,
  `USU_DCBLOCO` int DEFAULT NULL,
  `USU_DCNIVEL` varchar(100) DEFAULT NULL,
  `USU_DTCADASTRO` datetime DEFAULT NULL,
  `USU_DCSENHA` varchar(100) DEFAULT NULL,
  `USU_DCEMAIL` varchar(100) DEFAULT NULL,
  `USU_DCREDEF_TOKEN` varchar(200) DEFAULT NULL,
  `USU_DTREDEF_TOKEN_EXP` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `CON_CONCILIACAO`
  ADD PRIMARY KEY (`CON_IDCONCILIACAO`);

--
-- Índices de tabela `eventos`
--
ALTER TABLE `eventos`
  ADD PRIMARY KEY (`id`);

--
-- Índices de tabela `FUR_FUNDO_RESERVA`
--
ALTER TABLE `FUR_FUNDO_RESERVA`
  ADD PRIMARY KEY (`FUR_IDFUNDO_RESERVA`);

--
-- Índices de tabela `LIS_LISTACONVIDADOS`
--
ALTER TABLE `LIS_LISTACONVIDADOS`
  ADD PRIMARY KEY (`LIS_IDLISTACONVIDADOS`);

--
-- Índices de tabela `LOG_LOGSISTEMA`
--
ALTER TABLE `LOG_LOGSISTEMA`
  ADD PRIMARY KEY (`LOG_IDLOG`);

--
-- Índices de tabela `PUB_PUBLICIDADE`
--
ALTER TABLE `PUB_PUBLICIDADE`
  ADD PRIMARY KEY (`PUB_IDPUBLICIDADE`);

--
-- Índices de tabela `REP_REPORT`
--
ALTER TABLE `REP_REPORT`
  ADD PRIMARY KEY (`REP_IDREPORT`);

--
-- Índices de tabela `USU_USUARIO`
--
ALTER TABLE `USU_USUARIO`
  ADD PRIMARY KEY (`USU_IDUSUARIO`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `CON_CONCILIACAO`
--
ALTER TABLE `CON_CONCILIACAO`
  MODIFY `CON_IDCONCILIACAO` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=306;

--
-- AUTO_INCREMENT de tabela `eventos`
--
ALTER TABLE `eventos`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

--
-- AUTO_INCREMENT de tabela `FUR_FUNDO_RESERVA`
--
ALTER TABLE `FUR_FUNDO_RESERVA`
  MODIFY `FUR_IDFUNDO_RESERVA` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT de tabela `LIS_LISTACONVIDADOS`
--
ALTER TABLE `LIS_LISTACONVIDADOS`
  MODIFY `LIS_IDLISTACONVIDADOS` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=71;

--
-- AUTO_INCREMENT de tabela `LOG_LOGSISTEMA`
--
ALTER TABLE `LOG_LOGSISTEMA`
  MODIFY `LOG_IDLOG` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=338;

--
-- AUTO_INCREMENT de tabela `PUB_PUBLICIDADE`
--
ALTER TABLE `PUB_PUBLICIDADE`
  MODIFY `PUB_IDPUBLICIDADE` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT de tabela `REP_REPORT`
--
ALTER TABLE `REP_REPORT`
  MODIFY `REP_IDREPORT` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT de tabela `USU_USUARIO`
--
ALTER TABLE `USU_USUARIO`
  MODIFY `USU_IDUSUARIO` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=355;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
